language: python

matrix:
  include:
    - env: TOXENV=codestyle

    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9
      env: TOXENV=py39
    - python: pypy
      env: TOXENV=pypy
    - python: pypy3
      env: TOXENV=pypy3

install: travis_retry pip install tox
script: tox

notifications:
  email: false

pip3 install --user --upgrade launchable~=1.0

LAUNCHABLE_TOKEN=v1:test-it-out/test-it-out:3889270a047e486096179911397da453

launchable verify || true
